---
".zsh/zsh-autosuggestions":
  type: git-repo
  url: https://github.com/zsh-users/zsh-autosuggestions

".local/share/fonts/hacknerdfont":
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz
  exclude: ["**/LICENSE", "**/*.md"]

".tmux/plugins/tpm":
  type: git-repo
  url: https://github.com/tmux-plugins/tpm

".config/kitty/theme.conf":
  type: file
  url: https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/OneDark.conf
  refreshPeriod: 168h
