---
".oh-my-zsh":
  type: archive
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  stripComponents: 1
  refreshPeriod: 168h
".local/scripts":
  type: archive
  url: https://github.com/benchoncy/useful-scripts/archive/main.tar.gz
  stripComponents: 1
  executable: True
  exclude: ["**/LICENSE", "**/*.md"]
".notes":
  type: git-repo
  url: git@github.com:benchoncy/notes.git
