#!/usr/bin/env zsh
# ~/.zshrc

# oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="zhann"
HIST_STAMPS="yyyy-mm-dd"

zstyle ':omz:update' mode disabled

# enable completions
autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit

# enable plugins
plugins=(zsh-autosuggestions)

source $HOME/.config/shell/init.sh
source $ZSH/oh-my-zsh.sh
