#!/usr/bin/env zsh
# ~/.zshrc

# Enable autosuggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# enable completions
autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit

source $HOME/.config/shell/init.sh

eval "$(starship init zsh)"
