#!/usr/bin/env bash
# Finds assigned jira tickets and optionally opens tickets in the browser


# Check jira cli is installed
if ! command -v jira &> /dev/null
then
    echo "jira cli could not be found!"
    echo "Please install jira cli: https://github.com/ankitpokhrel/jira-cli"
    exit 1
fi

# Get jira tickets assigned to me
jira_ticket=$(jira issue list \
    -q 'assignee = currentUser() AND resolution = Unresolved AND project IS NOT EMPTY' \
    --plain \
    --no-headers \
    --columns key,summary \
    | fzf --prompt="Ticket > " --print-query | awk '{print $1}' | tail -1 | xargs)

echo "$jira_ticket"
