alias t="tmux"
alias ta="tmux attach"
alias tn="tmux new-session -A -s"
alias td="tmux detach-client"
alias tl="tmux list-sessions"
alias tkill="tmux kill-session -t"
alias ts="tmux-sessionizer"
alias tw="tmux-windowizer"
